In [1]:
import torch
test = torch.empty(2,2)
test

tensor([[0., 0.],
        [0., 0.]])

In [4]:
x = torch.tensor([[1,2]])
print(x)

tensor([[1, 2]])


In [5]:
c = torch.randint(low=0,high=10,size=(3,4))
c

tensor([[2, 7, 9, 4],
        [9, 3, 5, 9],
        [3, 8, 5, 1]])

In [7]:
#正态分布
e = torch.randn((3,4))
e

tensor([[ 1.2563, -0.7508,  0.4316,  2.3161],
        [-0.5609, -0.3634, -1.3379, -0.0377],
        [-0.8259, -0.2609, -0.5271,  1.0138]])

In [ ]:
#numpy数组转换为torch张量
